import Head from 'next/head'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { FC } from 'react'
import { Card } from '../components/Card'
import { CoffeeShop, CoffeeShops } from '../types'
import { GetStaticProps } from 'next'
import { GraphQLClient, gql } from 'graphql-request'
import { ThemeToggle } from '../components/ThemeToggle'

export const getStaticProps: GetStaticProps = async () => {
  const endpoint =
    'https://api-us-east-1.hygraph.com/v2/clcjt8ric0ogl01ughxd0esvh/master'

  const QUERY = gql`
    {
      coffeeShops {
        title
        website
        directions
        address
      }
    }
  `

  try {
    const client = new GraphQLClient(endpoint)
    const { coffeeShops } = await client.request<CoffeeShops>(QUERY)

    return {
      props: {
        coffeeShops,
      },
    }
  } catch (error) {
    console.error('Error retrieving data from the API:', error)
    return {
      props: {
        coffeeShops: [],
      },
    }
  }
}

export const Home: FC<{ coffeeShops: CoffeeShop[] }> = ({ coffeeShops }) => {
  console.log('CoffeeShop Data: ', coffeeShops)
  return (
    <>
      <Head>
        <title>The Coffee Seeker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'%3E%3Ctext y='.9em' font-size='90'%3E☕️%3C/text%3E%3C/svg%3E"
        />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@300&family=Lora:wght@600&family=Noto+Sans+Mono&display=swap"
          rel="stylesheet"
        />
      </Head>
      <header className={styles.header}>
        <h1>
          <span className={styles.logoText}>The Coffee Seeker</span>☕️
        </h1>
        {/* <ThemeToggle /> */}
      </header>
      <main className={styles.main}>
        <h2 className={styles.intro}>Leading a 🐎 to ☕️.</h2>
        <div className={styles.cardWrap}>
          <ul className={styles.cardList}>
            {coffeeShops.map((shop: CoffeeShop) => (
              <li key={shop.title}>
                <Card>
                  <div className={styles.shop}>
                    <h3 className={styles.shopTitle}>{shop.title}</h3>
                    <span className={styles.shopAddress}>{shop.address}</span>
                    <div className={styles.shopLinks}>
                      <Link className={styles.website} href={shop.website}>
                        Website
                      </Link>
                      <Link
                        className={styles.directions}
                        href={shop.directions}
                      >
                        Directions
                      </Link>
                    </div>
                  </div>
                </Card>
              </li>
            ))}
          </ul>
        </div>
      </main>
    </>
  )
}

export default Home
