import Head from 'next/head'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { FC } from 'react'
import { Card } from '../components/Card'
import { CoffeeShop } from '../types'

export const Home: FC = () => {
  const [coffeeShops, setCoffeeShops] = useState<CoffeeShop[]>([])

  useEffect(() => {
    async function fetchData() {
      const response = await fetch('/api/shops')
      const data = await response.json()
      setCoffeeShops(data.coffeeShops)
    }

    fetchData()
  }, [])

  return (
    <>
      <Head>
        <title>The Coffee Seeker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@300&family=Lora:wght@600&family=Noto+Sans+Mono&display=swap"
          rel="stylesheet"
        />
      </Head>
      <header className={styles.header}>
        <h1>The Coffee Seeker ☕️</h1>
      </header>
      <main className={styles.main}>
        <h2 className={styles.intro}>Leading a 🐎 to ☕️.</h2>
        <ul className={styles.cardWrap}>
          {coffeeShops.map((shop: CoffeeShop) => (
            <li key={shop.title}>
              <Card>
                <div className={styles.shop}>
                  <h3>{shop.title}</h3>
                  <span>{shop.address}</span>
                  <div className={styles.shopLinks}>
                    <Link className={styles.website} href={shop.website}>
                      Website
                    </Link>
                    <Link className={styles.directions} href={shop.directions}>
                      Directions
                    </Link>
                  </div>
                </div>
              </Card>
            </li>
          ))}
        </ul>
      </main>
    </>
  )
}

export default Home
