import Head from 'next/head'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { FC } from 'react'
import { Card } from '../components/Card'
import { CoffeeShop, CoffeeShops } from '../types'
import { GetServerSideProps } from 'next'
import { GraphQLClient, gql } from 'graphql-request'

export const getServerSideProps: GetServerSideProps = async () => {
  const endpoint =
    'https://api-us-east-1.hygraph.com/v2/clcjt8ric0ogl01ughxd0esvh/master'

  const QUERY = gql`
    {
      coffeeShops {
        title
        website
        directions
        address
      }
    }
  `

  try {
    const client = new GraphQLClient(endpoint)
    const { coffeeShops } = await client.request<CoffeeShops>(QUERY)

    return {
      props: {
        coffeeShops,
      },
    }
  } catch (error) {
    console.error('Error retrieving data from the API:', error)
    return {
      props: {
        coffeeShops: [],
      },
    }
  }
}

export const Home: FC<{ coffeeShops: CoffeeShop[] }> = ({ coffeeShops }) => {
  console.log('CoffeeShop Data: ', coffeeShops)
  return (
    <>
      <Head>
        <title>The Coffee Seeker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@300&family=Lora:wght@600&family=Noto+Sans+Mono&display=swap"
          rel="stylesheet"
        />
      </Head>
      <header className={styles.header}>
        <h1>The Coffee Seeker ☕️</h1>
      </header>
      <main className={styles.main}>
        <h2 className={styles.intro}>Leading a 🐎 to ☕️.</h2>
        <ul className={styles.cardWrap}>
          {coffeeShops.map((shop: CoffeeShop) => (
            <li key={shop.title}>
              <Card>
                <div className={styles.shop}>
                  <h3 className={styles.shopTitle}>{shop.title}</h3>
                  <span className={styles.shopAddress}>{shop.address}</span>
                  <div className={styles.shopLinks}>
                    <Link className={styles.website} href={shop.website}>
                      Website
                    </Link>
                    <Link className={styles.directions} href={shop.directions}>
                      Directions
                    </Link>
                  </div>
                </div>
              </Card>
            </li>
          ))}
        </ul>
      </main>
    </>
  )
}

export default Home
