import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { gql, GraphQLClient } from 'graphql-request'
import Link from 'next/link'
import { FC } from 'react'

const inter = Inter({ subsets: ['latin'] })

const hygraph = new GraphQLClient(
  'https://api-us-east-1.hygraph.com/v2/clcjt8ric0ogl01ughxd0esvh/master'
)

const QUERY = gql`
  {
    coffeeShops {
      title
      website
      directions
      address
    }
  }
`

export async function getStaticProps() {
  const { coffeeShops } = await hygraph.request(QUERY)

  return {
    props: {
      coffeeShops,
    },
  }
}

export interface CoffeeShops {
  coffeeShops: [
    {
      title: string
      website: string
      directions: string
      address: string
    }
  ]
}

export const Home: FC<CoffeeShops> = ({ coffeeShops }) => {
  return (
    <>
      <Head>
        <title>The Coffee Seeker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {coffeeShops.map((shop) => (
          <ul>
            <li>
              <div className={styles.shop}>
                <h3>{shop.title}</h3>
                <span>{shop.address}</span>
                <Link href={shop.website}>Website</Link>
                <Link href={shop.directions}>Directions</Link>
              </div>
            </li>
          </ul>
        ))}
      </main>
    </>
  )
}

export default Home
